# Generated by Django 5.0.6 on 2024-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_alter_exam_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userexam',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
