# Generated by Django 5.0.6 on 2024-07-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_rename_text_question_option1_question_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
