# Generated by Django 5.0.6 on 2024-07-31 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0004_favouriteexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(max_length=200)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examapp.skills')),
            ],
        ),
    ]
