# Generated by Django 5.0.6 on 2024-08-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0005_concepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='exam_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examapp.exam'),
            preserve_default=False,
        ),
    ]
