# Generated by Django 5.0.6 on 2024-07-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0007_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_defination',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
