# Generated by Django 5.0.6 on 2024-07-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0009_roadmaplist_roadmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='roadmaplist',
            name='roadmap_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='roadmaplist',
            name='skill',
        ),
        migrations.AddField(
            model_name='roadmaplist',
            name='skill',
            field=models.ManyToManyField(to='examapp.skills'),
        ),
    ]
