# Generated by Django 5.0.6 on 2024-07-22 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0010_skills_roadmaplist_roadmap_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='roadmap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='examapp.roadmaplist'),
        ),
    ]
