rdata = {
        "Frontend": ["HTML", "CSS", "JavaScript", "React", "Angular", "Vue", "TypeScript", "Bootstrap", "Responsive Design", "GraphQL"],
        "Backend": ["Node.js", "Python", "Java", "C#", "PHP", "Ruby on Rails", "Spring Boot", "ASP.NET Core", "Go", "Django", "Flask", "SQL", "NoSQL", "RESTful APIs"],
        "DevOps": ["Linux", "Docker", "Kubernetes", "Terraform", "CI/CD", "Jenkins", "AWS", "Azure", "Google Cloud", "Ansible", "Prometheus", "Grafana"],
        "Full Stack": ["HTML", "CSS", "JavaScript", "React", "Node.js", "Express.js", "MongoDB", "PostgreSQL", "Django", "Flask", "TypeScript", "GraphQL"],
        "AI and Data Scientist": ["Python", "R", "TensorFlow", "PyTorch", "Scikit-learn", "Pandas", "NumPy", "Data Visualization", "Machine Learning", "Deep Learning", "Statistics", "SQL"],
        "Data Analyst": ["Python", "R", "Excel", "SQL", "Tableau", "Power BI", "Data Cleaning", "Data Visualization", "Statistics", "Pandas", "NumPy"],
        "Android": ["Java", "Kotlin", "Android SDK", "Android Studio", "Gradle", "SQLite", "Firebase", "APIs", "XML"],
        "iOS": ["Swift", "Objective-C", "Xcode", "Cocoa Touch", "SQLite", "Firebase", "APIs", "Core Data", "SwiftUI"],
        "PostgreSQL": ["SQL", "PL/pgSQL", "Database Design", "Performance Tuning", "Backup and Recovery", "Security", "Data Modeling"],
        "Blockchain": ["Solidity", "Ethereum", "Smart Contracts", "Cryptography", "Bitcoin", "Hyperledger", "Consensus Algorithms", "DApps"],
        "QA": ["Manual Testing", "Automated Testing", "Selenium", "JUnit", "TestNG", "Performance Testing", "Load Testing", "Bug Tracking", "CI/CD"],
        "Software Architect": ["System Design", "Design Patterns", "Microservices", "Cloud Architecture", "Scalability", "Security", "API Design", "DevOps"],
        "Cyber Security": ["Network Security", "Penetration Testing", "Ethical Hacking", "Cryptography", "Incident Response", "Security Policies", "Firewall Management"],
        "UX Design": ["User Research", "Wireframing", "Prototyping", "Adobe XD", "Sketch", "Figma", "Usability Testing", "Interaction Design"],
        "Game Developer": ["Unity", "Unreal Engine", "C#", "C++", "Game Design", "3D Modeling", "Animation", "AI for Games", "Graphics Programming"],
        "Technical Writer": ["Technical Writing", "Documentation Tools", "API Documentation", "Markdown", "Content Management", "Editing", "Research"],
        "MLOps": ["Machine Learning", "CI/CD", "Docker", "Kubernetes", "TensorFlow", "PyTorch", "Model Deployment", "Model Monitoring", "AWS", "Azure"],
        "Product Manager": ["Product Lifecycle", "Agile Methodology", "Scrum", "Market Research", "Roadmapping", "Stakeholder Management", "User Stories"],
        "Developer Relations": ["Public Speaking", "Community Building", "Technical Writing", "Open Source Contribution", "Social Media", "Event Organization"],
        "Computer Science": ["Data Structures", "Algorithms", "Operating Systems", "Computer Networks", "Database Systems", "Theory of Computation"],
        "React": ["JavaScript", "JSX", "React Hooks", "Redux", "Context API", "React Router", "Testing Library", "TypeScript"],
        "Angular": ["TypeScript", "Components", "Services", "RxJS", "Angular CLI", "Forms", "Routing", "Testing"],
        "Vue": ["JavaScript", "Vue CLI", "Components", "Vuex", "Vue Router", "Composition API", "Directives", "Testing"],
        "JavaScript": ["ES6+", "DOM Manipulation", "Event Handling", "Asynchronous Programming", "Fetch API", "Web APIs", "JavaScript Frameworks"],
        "Node.js": ["JavaScript", "Express.js", "Asynchronous Programming", "RESTful APIs", "Database Integration", "Security", "Testing"],
        "TypeScript": ["JavaScript", "Static Typing", "Interfaces", "Classes", "Generics", "Modules", "Type Inference"],
        "Python": ["Syntax and Semantics", "Standard Library", "Web Frameworks", "Data Science Libraries", "Testing", "Automation"],
        "SQL": ["Queries", "Joins", "Indexes", "Stored Procedures", "Transactions", "Normalization", "Database Design"],
        "System Design": ["Scalability", "Load Balancing", "Caching", "Database Design", "Microservices", "API Design", "Security"],
        "API Design": ["RESTful APIs", "GraphQL", "Swagger/OpenAPI", "API Versioning", "Authentication", "Rate Limiting", "Documentation"],
        "ASP.NET Core": ["C#", ".NET Core", "MVC", "Entity Framework", "Razor Pages", "Web API", "Identity", "Testing"],
        "Java": ["OOP", "Java SE", "Java EE", "Spring Framework", "Hibernate", "JPA", "Concurrency", "Testing"],
        "C++": ["Syntax and Semantics", "STL", "OOP", "Memory Management", "Concurrency", "Templates", "C++11/14/17"],
        "Flutter": ["Dart", "Widgets", "State Management", "Flutter SDK", "Animations", "Plugins", "Testing"],
        "Spring Boot": ["Java", "Spring Framework", "Spring MVC", "Spring Data", "Spring Security", "Microservices", "Testing"],
        "Go": ["Syntax and Semantics", "Concurrency", "Standard Library", "Web Development", "Testing", "Deployment"],
        "Rust": ["Syntax and Semantics", "Ownership and Borrowing", "Concurrency", "Systems Programming", "WebAssembly"],
        "GraphQL": ["Schema Definition", "Queries and Mutations", "Resolvers", "Apollo Client", "Subscriptions", "Security"],
        "Design and Architecture": ["System Design", "Design Patterns", "Architectural Styles", "Scalability", "Security"],
        "Design System": ["UI Components", "Style Guides", "Theming", "Component Libraries", "Accessibility"],
        "React Native": ["JavaScript", "React", "Native Modules", "Navigation", "State Management", "Animations", "Testing"],
        "AWS": ["EC2", "S3", "RDS", "Lambda", "IAM", "CloudFormation", "DynamoDB", "VPC"],
        "Docker": ["Containers", "Dockerfile", "Docker Compose", "Image Management", "Networking", "Volumes"],
        "Kubernetes": ["Containers", "Pods", "Services", "Deployments", "ConfigMaps", "Secrets", "Helm"],
        "Linux": ["Shell Scripting", "System Administration", "Networking", "File Systems", "Security"],
        "MongoDB": ["NoSQL", "Document Model", "CRUD Operations", "Aggregation", "Indexing", "Replication"],
        "Prompt Engineering": ["AI Prompting", "Natural Language Processing", "Chatbot Development", "Conversational AI"],
        "Terraform": ["Infrastructure as Code", "Modules", "State Management", "Provisioning", "Providers"],
        "Data Structures & Algorithms": ["Arrays", "Linked Lists", "Trees", "Graphs", "Sorting", "Searching", "Dynamic Programming"],
        "Backend Performance": ["Caching", "Load Balancing", "Database Optimization", "Profiling", "Concurrency"],
        "Frontend Performance": ["Code Splitting", "Lazy Loading", "Compression", "Optimization Techniques"],
        "API Security": ["Authentication", "Authorization", "Rate Limiting", "Data Validation", "Encryption"]
    }